version: "3"
services:
  eureka:
    image: fabiopina151/eureka-server:0.1
    expose:
      - "8761"
  zuul:
    image: fabiopina151/zuul-gateway:0.1
    expose:
      - "4000"
    ports:
      - "8080:4000"
    links:
      - eureka
    environment:
      - EUREKA=eureka:8761
      - DATABASEADDRESS=192.168.1.32
  ms-db:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ribeiro
  users:
    image: fabiopina151/users-ms:0.1
    expose:
      - "5000"
    links:
      - ms-db
      - eureka
    environment:
      - DATABASEADDRESS=ms-db:3306
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5000
  songs:
    image: fabiopina151/songs-ms:0.1
    expose:
      - "5001"
    links:
      - ms-db
      - eureka
    environment:
      - DATABASEADDRESS=ms-db:3306
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5001
  playlists:
    image: fabiopina151/playlists-ms:0.1
    expose:
      - "5002"
    links:
      - ms-db
      - zuul
      - eureka
    environment:
      - DATABASEADDRESS=ms-db:3306
      - SONGSADDRESS=zuul:4000/songs-ms
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5002
  auth:
    image: fabiopina151/auth-ms:0.1
    expose:
      - "5003"
    links:
      - eureka
      - zuul
    environment:
      - USERSADDRESS=zuul:4000/users-ms
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5003
  aggr:
    image: fabiopina151/aggr-ms:0.1
    expose:
      - "5004"
    links:
      - eureka
      - zuul
    environment:
      - PLAYLISTSADDRESS=zuul:4000/playlists-ms
      - SONGSADDRESS=zuul:4000/songs-ms
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5004

