version: "3"
services:
  eureka:
    image: fabiopina151/eureka-server:0.1
    expose:
      - "8761" 
  zuul:
    image: fabiopina151/zuul-gateway:0.1
    expose:
      - "4000" 
    environment:
      - EUREKA=eureka:8761
      - DATABASEADDRESS=mariadb
      - TABLE=info
  registry:
    image: fabiopina151/service-registry:0.1
    environment:
      - EUREKA=eureka:8761
      - HEARTBEATINTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mariadb:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=data
