version: "3"
services:
  eureka:
    image: fabiopina151/eureka-server:0.1
    deploy: 
      restart_policy:
        condition: on-failure
    ports:
      - "8761:8761"
    networks:
      - my-network
  zuul:
    image: fabiopina151/zuul-gateway:0.1
    deploy: 
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8765"
    environment:
      - EUREKA=eureka:8761
      - DBADDRESS=mariadb
      - DBDATABASE=data
      - DBUSER=user
      - DBPASSWORD=password
      - DBTABLE=info
      - INFLUXDB_ADDRESS=influxdb
      - INFLUXDB_DB=db0
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    networks:
      - my-network
  registry:
    image: fabiopina151/service-registry:0.1
    deploy: 
      mode: global
      restart_policy:
        condition: on-failure
    labels:
      - "pt.fabiopina.mma.service.registry=true"
    environment:
      - EUREKA=eureka:8761
      - HEARTBEATINTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network
  mariadb:
    image: mariadb
    deploy: 
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=data
    networks:
      - my-network
  influxdb:
    image: influxdb
    deploy: 
      restart_policy:
        condition: on-failure
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    networks:
      - my-network
networks:
  my-network:
    external:
      name: my-network
