version: "3"
services:
  ms-db:
    image: mariadb
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=ribeiro
    networks:
      - my-network
  users:
    image: fabiopina151/users-ms:0.1
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
    labels:
      - "pt.fabiopina.mma.registry.eureka=true"
    environment:
      - DATABASEADDRESS=ms-db:3306
    networks:
      - my-network
  songs:
    image: fabiopina151/songs-ms:0.1
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
    labels:
      - "pt.fabiopina.mma.registry.eureka=true"
    environment:
      - DATABASEADDRESS=ms-db:3306
    networks:
      - my-network
  playlists:
    image: fabiopina151/playlists-ms:0.1
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
    labels:
      - "pt.fabiopina.mma.registry.eureka=true"
    environment:
      - DATABASEADDRESS=ms-db:3306
      - SONGSADDRESS=zuul:8765/music-songs
    networks:
      - my-network
  auth:
    image: fabiopina151/auth-ms:0.1
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
    labels:
      - "pt.fabiopina.mma.registry.eureka=true"
    environment:
      - USERSADDRESS=zuul:8765/music-users
    networks:
      - my-network
  aggr:
    image: fabiopina151/aggr-ms:0.1
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
    labels:
      - "pt.fabiopina.mma.registry.eureka=true"
    environment:
      - PLAYLISTSADDRESS=zuul:8765/music-playlists
      - SONGSADDRESS=zuul:8765/music-songs
    networks:
      - my-network
networks:
  my-network:
    external:
      name: my-network

