swagger: '2.0'
info:
  title: Log_Server
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      operationId: application.hello_world
      summary: "Hello World!"
      tags: [Log_Server]
      responses:
        200:
          description: OK
  /log:
    post:
      operationId: application.create_log_entry
      tags: [Log_Server]
      summary: "Creates a log entry"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/Log'
      responses:
        200:
          description: "OK."
        400:
          description: "Bad request."
        500:
          description: "Internal server error."
  /db:
    get:
      operationId: application.write_to_database
      summary: "Write parsed logs into database!"
      tags: [Log_Server]
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request."
        500:
          description: "Internal server error."
  /csv:
    get:
      operationId: application.write_to_csv
      summary: "Write parsed logs into csv!"
      tags: [Log_Server]
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request."
        500:
          description: "Internal server error."
    delete:
      operationId: application.delete_files
      summary: "Delete EventSequence.txt and 'Data.csv'!"
      tags: [Log_Server]
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request."
        500:
          description: "Internal server error."


definitions:
  Log:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
        example: "2018-04-27 11:22:14.196 [INCOMING] FROM-> 127.0.0.1 TO-> http://localhost:4000/users-ms/ METHOD-> GET"
        description: "Log message"
