server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST:}
    server:
      waitTimeInMsWhenSyncEmpty: 0