datasources:
- name: 'MySQL'
  type: 'mysql'
  url: 'mariadb:3306'
  database: 'db0'
  user: 'user'
  password: 'password'
- name: 'InfluxDB'
  type: 'influxdb'
  access: 'proxy'
  url: 'http://influxdb:8086'
  database: 'db0'
  user: 'user'
  password: 'password'
