{
 "title": "MY DASHBOARD",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "microservice",
    "label": "Microservice Name",
    "query": "SHOW TAG VALUES WITH KEY = \"destiny_microservice\""
   },
   {
    "name": "instance",
    "label": "Instance Name",
    "query": "SHOW TAG VALUES WITH KEY = \"destiny_instance\""
   },
   {
    "name": "method",
    "label": "Method",
    "query": "SHOW TAG VALUES WITH KEY = \"method\""
   },
   {
    "name": "code",
    "label": "Status Code",
    "query": "SHOW TAG VALUES WITH KEY = \"status_code\""
   }
  ]
 },
 "panels": [
  {
   "title": "Registered Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(start_date) as time_sec,\n  COUNT(DISTINCT(destiny_microservice)) as value,\n  'teste' as metric\nFROM t0\nWHERE $__timeFilter(start_date)\n"
    }
   ]
  },
  {
   "title": "Registered Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(start_date) as time_sec,\n  COUNT(DISTINCT(destiny_instance)) as value,\n  'teste' as metric\nFROM t0\nWHERE $__timeFilter(start_date)\n"
    }
   ]
  },
  {
   "title": "Request Number",
   "type": "graph",
   "description": "Number of requests per unit of time",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "destiny_microservice", "operator": "=~", "value": "/^$microservice$/" },
      { "condition": "AND", "key": "destiny_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$method$/" },
      { "condition": "AND", "key": "status_code", "operator": "=~", "value": "/^$code$/" }
     ]
    }
   ]
  },
  {
   "title": "Services Information",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  destiny_ip as 'Ip address',\n  destiny_instance as 'Instance',\n  destiny_port as 'Port',\n  destiny_microservice as 'Microservice'\nFROM t0\nWHERE $__timeFilter(start_date)\nGROUP BY destiny_ip"
    }
   ]
  },
  {
   "title": "Request Heatmap",
   "type": "heatmap",
   "description": "Each column represents an histogram of request duration for that period of time. Darker tones of red means more requests for that slot",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(start_date) as time_sec,\n  duration as value,\n  $scope as metric\nFROM info\nWHERE destiny_microservice LIKE $microservice\nAND destiny_instance LIKE $instance\nAND $__timeFilter(start_date)\n",
     "tags": [
      { "key": "destiny_microservice", "operator": "=~", "value": "/^$microservice$/" },
      { "condition": "AND", "key": "destiny_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$method$/" },
      { "condition": "AND", "key": "status_code", "operator": "=~", "value": "/^$code$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "graph",
   "description": "Distribution for the request duration",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(start_date) as time_sec,\n  duration as value,\n  $scope as metric\nFROM info\nWHERE destiny_microservice LIKE $microservice\nAND destiny_instance LIKE $instance\nAND $__timeFilter(start_date)\n",
     "tags": [
      { "key": "destiny_microservice", "operator": "=~", "value": "/^$microservice$/" },
      { "condition": "AND", "key": "destiny_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$method$/" },
      { "condition": "AND", "key": "status_code", "operator": "=~", "value": "/^$code$/" }
     ]
    }
   ]
  }
 ]
}