server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST:http://10.0.2.15:8761/eureka/}
    server:
      waitTimeInMsWhenSyncEmpty: 0